---
title: Розумний помічник
hero_image: images/banner.png
description: Створи розумного віртуального помічника, який реагує на команди
version: 4
listed: true
copyedit: true
last_tested: '2019-05-09'
steps:
- title: Що ти зробиш
- title: Створи проєкт
- title: Приклади команд
  completion:
  - engaged
- title: Навчи модель
- title: Створи помічника
- title: 'Додаткове завдання'
  challenge: true
- title: Показник імовірності
  completion:
  - external
