---
title: Slimme assistent
hero_image: images/banner.png
description: Maak een virtuele assistent die reageert op commando's
version: 4
listed: true
copyedit: true
last_tested: '2019-05-09'
steps:
- title: Wat ga je maken
- title: Het project opzetten
- title: Voorbeeldopdrachten
  completion:
  - engaged
- title: Train het model
- title: Maak de assistent
- title: 'Gebruik het machine learning-model in Scratch'
  challenge: true
- title: Betrouwbaarheidsscores
  completion:
  - internal
