---
title: Slimme klassenassistent
hero_image: images/banner.png
description: Maak een virtuele klassenassistent die op opdrachten reageert
version: 4
listed: true
copyedit: true
last_tested: "2019-05-09"
steps:
  - 
    title: Inleiding
  - 
    title: Hoe maak je een project
  - 
    title: Voeg een lijst met regels toe
  - 
    title: Verzamel voorbeelden voor training
  - 
    title: Train en test een machine learning-model
  - 
    title: Gebruik het machine learning-model in Scratch
  - 
    title: Hoe betrouwbaarheidsscores te gebruiken
  - 
    title: "Uitdaging: meer items om te besturen"
    challenge: true
  - 
    title: Wat kun je verder nog doen?
