---
title: Slimme klassenassistent
hero_image: images/banner.png
description: Maak een virtuele klassenassistent die op opdrachten reageert
version: 4
listed: true
copyedit: true
last_tested: '2019-05-09'
steps:
- title: Inleiding
  completion: engaged
- title: Hoe maak je een project
- title: Voeg een lijst met regels toe
- title: Verzamel voorbeelden voor training
- title: Train en test een machine learning-model
- title: Gebruik het machine learning-model in Scratch
  completion: internal
- title: Hoe betrouwbaarheidsscores te gebruiken
- title: 'Uitdaging: meer items om te controleren'
  challenge: true
- title: Wat kun je verder nog doen?
