---
title: Smart classroom assistant
hero_image: images/banner.png
description: Create a virtual classroom assistant that reacts to commands
version: 4
listed: true
copyedit: true
last_tested: '2019-05-09'
steps:
- title: Introduction
- title: Set up the project
- title: Example commands
  completion:
  - engaged
- title: Train the model
- title: Create the assistant
- title: How to use confidence scores
  completion:
  - internal
- title: 'Challenge: more items to control'
  challenge: true
- title: What next?
