---
title: Smart classroom assistant
hero_image: images/banner.png
description: Create a virtual classroom assistant that reacts to commands
version: 4
listed: true
copyedit: true
last_tested: '2019-05-09'
steps:
- title: Introduction
- title: Set up the project
- title: Train your assistant
  completion:
  - engaged
- title: Train and test a machine learning model
- title: Use the machine learning model in Scratch
- title: How to use confidence scores
  completion:
  - internal
- title: 'Challenge: more items to control'
  challenge: true
- title: What next?
